
## Gopkg.toml example (these lines may be deleted)

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Dependencies define constraints on dependent projects. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[dependencies]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"

## Overrides have the same structure as [[dependencies]], but supercede all
## [[dependencies]] declarations from all projects. Only the current project's
## [[overrides]] are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[overrides]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overriden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"

[[dependencies]]
  branch = "master"
  name = "github.com/RichardKnop/go-fixtures"

[[dependencies]]
  branch = "master"
  name = "github.com/RichardKnop/jsonhal"

[[dependencies]]
  branch = "master"
  name = "github.com/RichardKnop/logging"

[[dependencies]]
  name = "github.com/RichardKnop/uuid"

[[dependencies]]
  name = "github.com/coreos/etcd"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/context"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/sessions"

[[dependencies]]
  name = "github.com/hashicorp/consul"

[[dependencies]]
  branch = "master"
  name = "github.com/jinzhu/gorm"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  name = "github.com/mattn/go-sqlite3"

[[dependencies]]
  branch = "master"
  name = "github.com/oxtoacart/bpool"

[[dependencies]]
  branch = "master"
  name = "github.com/phyber/negroni-gzip"

[[dependencies]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[dependencies]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/cli"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/negroni"

[[dependencies]]
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  branch = "master"
  name = "gopkg.in/tylerb/graceful.v1"
